const FRONT_LOGIN = "/"
const FRONT_ERROR = "/*"
const FRONT_RESET_PASSWORD = "/reset-password"

// LOGGED USER

const FRONT_HOME = "/home"
const FRONT_TRAINER_PRATICAL_LIFE = "/trainer-pratical-life"

const FRONT_FORMATION_DETAIL = "/formations/:id"
const FRONT_FORMATION_DETAIL_PROMOTION_DETAIL = "/formations/:formationId/promotions/:promotionId"


// ADMIN

const FRONT_ADMIN_USERS = "/admin/users"
const FRONT_ADMIN_USERDETAILS ="/admin/users/:id"
const FRONT_ADMIN_ADD_USERS = "/admin/users/add"
const FRONT_ADMIN_DASHBOARD = "/admin/dashboard"
const FRONT_ADMIN_TRAINING= "/admin/training"
const FRONT_ADMIN_EVALUATION = "/admin/evaluation"
const FRONT_ADMIN_PROMOTION= "/admin/promotions"
const FRONT_ADMIN_ADD_TRAINING = "/admin/training/add"


export {FRONT_LOGIN, FRONT_ERROR, FRONT_RESET_PASSWORD, FRONT_HOME, FRONT_TRAINER_PRATICAL_LIFE, FRONT_FORMATION_DETAIL, FRONT_FORMATION_DETAIL_PROMOTION_DETAIL, FRONT_ADMIN_USERS, FRONT_ADMIN_ADD_USERS, FRONT_ADMIN_DASHBOARD, FRONT_ADMIN_EVALUATION, FRONT_ADMIN_TRAINING, FRONT_ADMIN_PROMOTION, FRONT_ADMIN_USERDETAILS, FRONT_ADMIN_ADD_TRAINING}