const FRONT_LOGIN_PAGE = "/"
const FRONT_ERROR = "/*"

// LOGGED USER

const FRONT_HOME_PAGE = "/home"
const FRONT_TRAINER_PRATICAL_LIFE = "/trainer-pratical-life"


// ADMIN

const FRONT_ADMIN_USERS = "/admin/users"
const FRONT_ADMIN_ADD_USERS = "/admin/users/add"

export {FRONT_LOGIN_PAGE, FRONT_ERROR, FRONT_HOME_PAGE, FRONT_TRAINER_PRATICAL_LIFE,FRONT_ADMIN_USERS, FRONT_ADMIN_ADD_USERS}